# Generated by Django 4.2.4 on 2024-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='department',
            field=models.IntegerField(choices=[(1, 'Managers'), (2, 'Team Leads'), (3, 'Employees')]),
        ),
    ]
