# Generated by Django 4.2.4 on 2024-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('SciFi', 'Scifi')], default='Fantasy', max_length=10),
            preserve_default=False,
        ),
    ]
